### ISSUE TITLE
After going through all the issues, this is my conclusion

### ISSUE THREAD

**Issue by t1amat9409** [illuspas/Node-Media-Server#148]
Some rtmp clients fail to make a successful stream, well not that the stream fails, but the transmuxing does, I noticed it after a few tries though.

First I was using OBS, I could play the rtmp://...../Stream on vlc, meaning the server is working. But files not being generated. I edit the node_server_trans_sessions file, for further debugging... Still nothing.

I changed all permissions for the "media" folder, everything to READ/WRITE. Then tried again, still nothing. Then I decide to open my terminal, then stream a video on my laptop. Boom, The files were being generated. I don't know what I did correct, but I hope we figure this out, this is such a great package, very great for all of us.

I'm using Linux server, ubuntu 16.X.X, and node 8 at the moment.

I hope everyone get their luck!

Thanks to the creator...

**Comment by chevonc** [comment]
If you're using the latest package, the issue here is the the `setTimeout` function used to determine the codecs coming over the OBS stream in the first few frames is too low (200ms). See my PR here, where I raise it to 5 seconds to give ample time for a variety of connection speeds.

See - https://github.com/illuspas/Node-Media-Server/pull/149/files#diff-1db824b0e568289ac2f7e4ac6035ae3dL1040

**Comment by t1amat9409** [comment]
@chevonc so it worked?

**Comment by chevonc** [comment]
Yes, it works. But there were changes recently that caused a break. If the author merges my PR or you use my branch, it will work as expected

**Comment by t1amat9409** [comment]
I will do that. Thanks!

**Comment by chrisspiegl** [comment]
Hello @t1amat9409 , could you get it work for you? Please close the issue then.

**Comment by t1amat9409** [comment]
@chrisspiegl Yeah I did... I'll now close the issue
