### ISSUE TITLE
ffmpeg requires version 4.0.0 above

### ISSUE THREAD

**Issue by TheresaQWQ** [illuspas/Node-Media-Server#172]
日志：
```
3/17/2019 03:04:45 13801 [INFO] Node Media Server v1.4.12
3/17/2019 03:04:45 13801 [INFO] Node Media Rtmp Server started on port: 1935
3/17/2019 03:04:45 13801 [INFO] Node Media Http Server started on port: 8000
3/17/2019 03:04:45 13801 [INFO] Node Media WebSocket Server started on port: 8000
3/17/2019 03:04:45 13801 [ERROR] Node Media Trans Server startup failed. ffmpeg requires version 4.0.0 above
3/17/2019 03:04:45 13801 [ERROR] Download the latest ffmpeg static program: https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz | https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz
```
app.js：
```
const { NodeMediaServer } = require('node-media-server');

const config = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 60,
    ping_timeout: 30
  },
  http: {
    port: 8000,
    allow_origin: '*'
  },
  trans: {
    ffmpeg: '/usr/bin/ffmpeg',
    tasks: [
      {
        app: 'live',
        hls: true,
        hlsFlags: '[hls_time=2:hls_list_size=3:hls_flags=delete_segments]',
        dash: true,
        dashFlags: '[f=dash:window_size=3:extra_window_size=5]'
      }
    ]
  }
};

var nms = new NodeMediaServer(config)
nms.run();
```

**Comment by kekhong95** [comment]
reinstall ffmpeg using static install , default version is 3.2.1 lower 4.0

**Comment by chrisspiegl** [comment]
@TheresaQWQ did you figure out what the problem was for you? Maybe close this issue or give us an explanation, please. Thank you.

**Comment by chrisspiegl** [comment]
Ok, now I did a few tests.

When FFmpeg 3.x is installed, then an error message is shown that FFmpeg 4.x is necessary to use Node Media Server. It also gives download links to statics which are no longer working.

Best would be to replace the static download link with something like this:

`https://johnvansickle.com/ffmpeg/`

Since this page actually offers the different files which the user may need for their system.

The change would be around this area:

https://github.com/illuspas/Node-Media-Server/blob/890d70082dd4cac07dcf020e35d872c3b51783bc/node_core_utils.js#L70

Either link to the download link to begin with, or add arm64 would be an idea as well (I am running on an arm64 server from scaleway).

**Comment by hthetiot** [comment]
@TheresaQWQ the docker version use ffmpeg 4 with RTMPS support see https://github.com/illuspas/Node-Media-Server/pull/356
