### ISSUE TITLE
Hls.js player doesn't load the stream if the first segment of hls doesn't exist

### ISSUE THREAD

**Issue by MisterKirill** [illuspas/Node-Media-Server#610]
Probably a problem with Hls.js, but when I'm trying to load stream in player like this:
```js
if(Hls.isSupported()) {
  const hls = new Hls();
  hls.loadSource(url);
  hls.attachMedia(videoRef.current);
} else if (videoRef.current.canPlayType('application/vnd.apple.mpegurl')) {
  videoRef.current.src = url;
}
```
it works perfectly only if the first segment is exist in playlist, and if there is no first segment, it loads only like 5 seconds of black screen:
![Screenshot 2023-11-19 142504](https://github.com/illuspas/Node-Media-Server/assets/87936030/41f8ed37-ced8-410b-9ad0-5cdcbea5589b)

Node media server configuration:
```js
const config = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 30,
    ping_timeout: 60
  },
  http: {
    port: 8000,
    mediaroot: './media',
    allow_origin: '*'
  },
  trans: {
    ffmpeg: 'ffmpeg.exe',
    tasks: [
      {
        app: 'live',
        hls: true,
        hlsFlags: '[hls_time=2:hls_list_size=3:hls_flags=delete_segments]',
      }
    ]
  },
}
```

**Comment by TideOPL** [comment]
How did you fix this, if you did?

**Comment by TideOPL** [comment]
For future reference and people that have the same problem, I have a fix! It seems the command that NMS uses to transcode FLV to HLS is causing problems. The fix is as follows:

In NMS, look for node_trans_session.js.

Around line 67 it sets loads of arguments to run. I will paste what I have below and you can change it for whatever you need.

```
    let argv = ['-i', inPath];
    // Array.prototype.push.apply(argv, ['-c:v', vc]);
    // Array.prototype.push.apply(argv, this.conf.vcParam);
    // Array.prototype.push.apply(argv, ['-c:a', ac]);
    // Array.prototype.push.apply(argv, this.conf.acParam);
    Array.prototype.push.apply(argv, ['-c:v', 'h264', '-c:a', 'aac', '-strict', '-2', '-f', 'hls', '-x264-params', 'keyint=15:min-keyint=15', '-hls_time', '1', '-hls_flags', 'delete_segments', '-hls_list_size', '20', '-http_persistent', '0', mapStr]);
```

![image](https://github.com/illuspas/Node-Media-Server/assets/57710757/7f867c49-50ee-44d9-acab-b98ae8cc771c)

Maybe someone could look into the real problem and create a pull request to fix it.
